export const mockLaunches = [
  {
    id: "1",
    name: "FalconSat",
    date: "2006-03-24",
    rocket: "Falcon 1",
    success: false,
    patch: "public\globe.svg",
    isFavorite: false,
    details: "Engine failure at 33 seconds and loss of vehicle.",
    wikipedia: "https://en.wikipedia.org/wiki/DemoSat",
    webcast: "https://www.youtube.com/watch?v=0a_00nJ_Y88",
  },
  {
    id: "2",
    name: "DemoSat",
    date: "2007-03-21",
    rocket: "Falcon 1",
    success: false,
    patch: "public\globe.svg",
    isFavorite: true,
    details: "Failed to reach orbit due to fuel leak and fire.",
    wikipedia: "https://en.wikipedia.org/wiki/DemoSat",
    webcast: "https://www.youtube.com/watch?v=Lk4zQ2wP-Nc",
  },
  {
    id: "3",
    name: "Trailblazer",
    date: "2008-08-03",
    rocket: "Falcon 1",
    success: false,
    patch: "public\globe.svg",
    isFavorite: false,
    details: "Failed during stage separation.",
    wikipedia: "https://en.wikipedia.org/wiki/Trailblazer_(satellite)",
    webcast: "https://www.youtube.com/watch?v=v0w9p3U8860",
  },
  {
    id: "4",
    name: "RatSat",
    date: "2008-09-28",
    rocket: "Falcon 1",
    success: true,
    patch: "public\globe.svg",
    isFavorite: false,
    details: "First successful launch reaching orbit.",
    wikipedia: "https://en.wikipedia.org/wiki/Ratsat",
    webcast: "https://www.youtube.com/watch?v=dLQ2tZEH6G0",
  },
];
